from enum import Enum


class GameState(str, Enum):
    PLAYERS_WAITING = 'PLAYERS_WAITING'
    IN_PROCESS = 'IN_PROCESS'
    PREPARATORY_STAGE = 'PREPARATORY_STAGE'
    CAPTURING_STAGE = 'CAPTURING_STAGE'
    MARKS_WAITING = 'MARKS_WAITING'
    BATTLING_STAGE = 'BATTLING_STAGE'
    DUELING = 'DUELING'
    ANSWERS_WAITING = 'ANSWERS_WAITING'
    ENDED = 'ENDED'


class StageType(str, Enum):
    PREPARATORY = 'PREPARATORY'
    CAPTURING = 'CAPTURING'
    BATTLINGS = 'BATTLINGS'


class StageName(str, Enum):
    PREPARATORY = 'PREPARATORY'
    CAPTURING = 'CAPTURING'
    BATTLINGS = 'BATTLINGS'


class ResultType(str, Enum):
    CAPTURED = 'CAPTURED'
    DEFENDED = 'DEFENDED'


class RoundType(str, Enum):
    ORDERED = 'ORDERED'
    UNORDERED = 'UNORDERED'
