version: '3'
services:
  viva-victoria-games:
    container_name: viva-victoria-games
    image: smwatertd/viva-victoria-games:latest
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 8
    restart: unless-stopped
    ports:
      - 8000:8000
    build:
      context: ../
      dockerfile: docker/Dockerfile
