"""add games

Revision ID: 67bd12812d1c
Revises: 182b4b90096e
Create Date: 2023-11-24 01:11:34.981994

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67bd12812d1c'
down_revision: Union[str, None] = '182b4b90096e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'games',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.Column('state', sa.String(), server_default='players_waiting', nullable=False),
        sa.Column('round_number', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('pk'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
