"""add players connected_at field

Revision ID: c302c701b00e
Revises: ace384ee1d5c
Create Date: 2023-12-21 17:08:20.102355

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c302c701b00e'
down_revision: Union[str, None] = 'ace384ee1d5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('connected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'connected_at')
    # ### end Alembic commands ###
