"""add questions

Revision ID: cc4ad4e15f13
Revises: 67bd12812d1c
Create Date: 2023-11-24 01:14:44.772589

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4ad4e15f13'
down_revision: Union[str, None] = '67bd12812d1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'questions',
        sa.Column('pk', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('pk'),
    )
    op.add_column('games', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'questions', ['question_id'], ['pk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'question_id')
    op.drop_table('questions')
    # ### end Alembic commands ###
