"""add fields value field

Revision ID: ace384ee1d5c
Revises: f2bed77b237f
Create Date: 2023-12-21 15:14:40.338456

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace384ee1d5c'
down_revision: Union[str, None] = 'f2bed77b237f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('value', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'value')
    # ### end Alembic commands ###
