"""add games creator_id field

Revision ID: 1bad1c98f1d5
Revises: c302c701b00e
Create Date: 2023-12-25 18:24:02.046614

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bad1c98f1d5'
down_revision: Union[str, None] = 'c302c701b00e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('creator_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'creator_id')
    # ### end Alembic commands ###
