"""remove questions

Revision ID: f59f298f0f5c
Revises: 18b4f06a89cb
Create Date: 2023-12-19 16:09:35.616606

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f59f298f0f5c'
down_revision: Union[str, None] = '18b4f06a89cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('duels_category_id_fkey', 'duels', type_='foreignkey')
    op.drop_constraint('duels_question_id_fkey', 'duels', type_='foreignkey')
    op.drop_constraint('players_answer_id_fkey', 'players', type_='foreignkey')
    op.drop_constraint('answers_question_id_fkey', 'answers', type_='foreignkey')
    op.drop_table('categories')
    op.drop_table('questions')
    op.drop_table('answers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id', name='categories_pkey'),
    )
    op.create_table(
        'questions',
        sa.Column(
            'id',
            sa.INTEGER(),
            server_default=sa.text("nextval('questions_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id', name='questions_pkey'),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        'answers',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column('is_correct', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name='answers_question_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='answers_pkey'),
    )
    op.create_foreign_key('players_answer_id_fkey', 'players', 'answers', ['answer_id'], ['id'])
    op.create_foreign_key('duels_question_id_fkey', 'duels', 'questions', ['question_id'], ['id'])
    op.create_foreign_key('duels_category_id_fkey', 'duels', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
