"""remove games question_id

Revision ID: 4ad64efd1b0f
Revises: 96010ca55078
Create Date: 2023-12-13 16:00:14.759627

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ad64efd1b0f'
down_revision: Union[str, None] = '96010ca55078'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('games_question_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('games_question_id_fkey', 'games', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
