"""add duels

Revision ID: 96010ca55078
Revises: f063b8f45382
Create Date: 2023-12-13 15:45:53.308543

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96010ca55078'
down_revision: Union[str, None] = 'f063b8f45382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories', sa.Column('id', sa.Integer(), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'duels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=True),
        sa.Column('attacker_id', sa.Integer(), nullable=True),
        sa.Column('defender_id', sa.Integer(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.Column('field_id', sa.Integer(), nullable=True),
        sa.Column('round_number', sa.Integer(), server_default='0', nullable=True),
        sa.ForeignKeyConstraint(
            ['attacker_id'],
            ['players.id'],
        ),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['categories.id'],
        ),
        sa.ForeignKeyConstraint(
            ['defender_id'],
            ['players.id'],
        ),
        sa.ForeignKeyConstraint(
            ['field_id'],
            ['fields.id'],
        ),
        sa.ForeignKeyConstraint(
            ['game_id'],
            ['games.id'],
        ),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['questions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('players', sa.Column('answer_id', sa.Integer(), nullable=True))
    op.drop_constraint('players_username_key', 'players', type_='unique')
    op.create_foreign_key(None, 'players', 'answers', ['answer_id'], ['id'])
    op.drop_column('players', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_unique_constraint('players_username_key', 'players', ['username'])
    op.drop_column('players', 'answer_id')
    op.drop_table('duels')
    op.drop_table('categories')
    # ### end Alembic commands ###
