"""add games

Revision ID: 2799b3e4eea0
Revises: 8393f8868c90
Create Date: 2023-11-25 22:03:46.581124

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2799b3e4eea0'
down_revision: Union[str, None] = '8393f8868c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'games',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'PLAYERS_WAITING',
                'IN_PROCESS',
                'ATTACK_WAITING',
                'DUELING',
                'ANSWERS_WAITING',
                'ENDED',
                name='gamestate',
            ),
            nullable=False,
        ),
        sa.Column('round_number', sa.Integer(), server_default='0', nullable=True),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['question_id'],
            ['questions.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
