"""add duels correct_answer_id field

Revision ID: f2bed77b237f
Revises: f59f298f0f5c
Create Date: 2023-12-19 17:30:04.885526

"""
from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2bed77b237f'
down_revision: Union[str, None] = 'f59f298f0f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('duels', sa.Column('correct_answer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('duels', 'correct_answer_id')
    # ### end Alembic commands ###
